export {default as HomePage} from './home'
export {default as LayoutPage} from './layout'
export {default as LoginPage} from './login'
export {default as RegisterPage} from './register'
export {default as Board} from './board'
export {default as NotFound} from './404'
export {default as Card} from './card'
export {default as Statistic} from './statisticPage'
